version: '2'

services:

  peer0.org1.de:
    container_name: peer0.org1.de
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.de
      - CORE_PEER_ADDRESS=peer0.org1.de:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.de:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.de:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.de:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.de/peers/peer0.org1.de/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.de/peers/peer0.org1.de/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.de:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.de:
    container_name: peer1.org1.de
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.de
      - CORE_PEER_ADDRESS=peer1.org1.de:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.de:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.de:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.de:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.de/peers/peer1.org1.de/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.de/peers/peer1.org1.de/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.de:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.org2.de:
    container_name: peer0.org2.de
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.de
      - CORE_PEER_ADDRESS=peer0.org2.de:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.de:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.de:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.de:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.de/peers/peer0.org2.de/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.de/peers/peer0.org2.de/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.de:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.org2.de:
    container_name: peer1.org2.de
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.de
      - CORE_PEER_ADDRESS=peer1.org2.de:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.de:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.de:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.de:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.de/peers/peer1.org2.de/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.de/peers/peer1.org2.de/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.de:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.org3.de:
    container_name: peer0.org3.de
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.de
      - CORE_PEER_ADDRESS=peer0.org3.de:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.de:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.de:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.de:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.de/peers/peer0.org3.de/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.de/peers/peer0.org3.de/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.de:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.org3.de:
    container_name: peer1.org3.de
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.de
      - CORE_PEER_ADDRESS=peer1.org3.de:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.de:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.de:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.de:12051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.de/peers/peer1.org3.de/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.de/peers/peer1.org3.de/tls:/etc/hyperledger/fabric/tls
        - peer1.org3.de:/var/hyperledger/production
    ports:
      - 12051:12051