Organizations:
    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.member')"
                #Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.member')"
                #Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
        AnchorPeers:
            - Host: peer0.org1.de
              Port: 7051

    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.member')"
                #Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.member')"
                #Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"
        AnchorPeers:
            - Host: peer0.org2.de
              Port: 9051

    - &Org3
        Name: Org3MSP
        ID: Org3MSP
        MSPDir: crypto-config/peerOrganizations/org3.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org3MSP.member')"
                #Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org3MSP.member')"
                #Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org3MSP.admin')"
        AnchorPeers:
            - Host: peer0.org3.de
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities


Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
            - Host: orderer.org1.de
              Port: 7050
              ClientTLSCert: crypto-config/peerOrganizations/org1.de/peers/orderer.org1.de/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/org1.de/peers/orderer.org1.de/tls/server.crt
            - Host: orderer1.org1.de
              Port: 7050
              ClientTLSCert: crypto-config/peerOrganizations/org1.de/peers/orderer1.org1.de/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/org1.de/peers/orderer1.org1.de/tls/server.crt
            - Host: orderer.org2.de
              Port: 7050
              ClientTLSCert: crypto-config/peerOrganizations/org2.de/peers/orderer.org2.de/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/org2.de/peers/orderer.org2.de/tls/server.crt
            - Host: orderer1.org2.de
              Port: 7050
              ClientTLSCert: crypto-config/peerOrganizations/org2.de/peers/orderer1.org2.de/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/org2.de/peers/orderer1.org2.de/tls/server.crt
            - Host: orderer.org3.de
              Port: 7050
              ClientTLSCert: crypto-config/peerOrganizations/org3.de/peers/orderer.org3.de/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/org3.de/peers/orderer.org3.de/tls/server.crt
        Options:
            TickInterval: 500ms
            ElectionTick: 10
            HeartbeatTick: 1
            MaxInflightBlocks: 5
            SnapshotIntervalSize: 20 MB
    Addresses:
        - orderer.org1.de:7050
        - orderer1.org1.de:7050
        - orderer.org2.de:7050
        - orderer1.org2.de:7050
        - orderer.org3.de:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#   - This section is the important part since it refers to the above definition
#   . Configtxgen tool consumes these profiles.
#
################################################################################
Profiles:
    ThreeOrgsOrdererGenesisRAFT:
        <<: *ChannelDefaults
        # Policies:
        #     Readers:
        #         Type: Signature
        #         Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org3MSP.member')"
        #     Writers:
        #         Type: Signature
        #         Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org3MSP.member')"
        #     Admins:
        #         Type: ImplicitMeta
        #         Rule: "MAJORITY Admins"
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3

    ThreeOrgsChannel:
        <<: *ChannelDefaults
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('Org3MSP.member', 'Org2MSP.member', 'Org1MSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('Org3MSP.admin', 'Org3MSP.client', 'Org2MSP.admin', 'Org2MSP.client', 'Org1MSP.admin', 'Org1MSP.client')"
                Admins:
                    Type: ImplicitMeta
                    Rule: "MAJORITY Admins"
            Organizations:
                - *Org1
                - *Org2
                - *Org3
