PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.de
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer1
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.de
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer1
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org3
  # ---------------------------------------------------------------------------
  - Name: Org3
    Domain: org3.de
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
    Template:
      Count: 2
    Users:
      Count: 1