version: '2'

volumes:
  orderer.org1.de:
  orderer.org2.de:
  orderer.org3.de:

networks:
  logichain:

services:

  orderer.org1.de:
    container_name: orderer.org1.de
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
    - ORDERER_GENERAL_LOCALMSPID=Org1MSP
    networks:
    - logichain
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/peerOrganizations/org1.de/peers/orderer.org1.de/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/peerOrganizations/org1.de/peers/orderer.org1.de/tls/:/var/hyperledger/orderer/tls
        - orderer.org1.de:/var/hyperledger/production/orderer
    ports:
    - 7050:7050

  orderer.org2.de:
    container_name: orderer.org2.de
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
    - ORDERER_GENERAL_LOCALMSPID=Org2MSP
    networks:
    - logichain
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/peerOrganizations/org2.de/peers/orderer.org2.de/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/peerOrganizations/org2.de/peers/orderer.org2.de/tls/:/var/hyperledger/orderer/tls
        - orderer.org2.de:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer.org3.de:
    container_name: orderer.org3.de
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
    - ORDERER_GENERAL_LOCALMSPID=Org3MSP
    networks:
    - logichain
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/peerOrganizations/org3.de/peers/orderer.org3.de/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/peerOrganizations/org3.de/peers/orderer.org3.de/tls/:/var/hyperledger/orderer/tls
        - orderer.org3.de:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
